name: CI builder

on: 
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      SPRING_PROFILES_ACTIVE: test
      SPRING_DATASOURCE_URL: ${variables.DATABASE_URL}
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.h2.Driver
      SPRING_DATASOURCE_USERNAME: ${variables.DATABASE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${variables.DATABASE_PASSWORD}
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.H2Dialect
      SPRING_JPA_HIBERNATE_DDL_AUTO: create-drop
      SPRING_MAIL_USERNAME: ${variables.DATABASE_USERNAME}
      SPRING_MAIL_PASSWORD: ${variables.DATABASE_PASSWORD}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven' #enable to not reload everything for every build

      - name: Build and run tests
        run: |
          mvn clean test
          # mvn spring-boot:run   #you can use it ton run the app after the test
